<div class="block-muon-tra">
    <h1>Mượn sách</h1>
    <form name="frm-muontra" action="post" method="">
        <input type="text" size="30px" style="text-align: center" name="mavach" id="barcode-input"/>
<?php
    $chitietdocgiaUrl = Mage::helper("adminhtml")->getUrl("thuvien/adminhtml_muontra/chitietdocgia");
    $urlTrasach =   Mage::helper("adminhtml")->getUrl("thuvien/adminhtml_muontra/tratpajax");
?>
    <input type="hidden" value="<?php echo $chitietdocgiaUrl ?>" name="chitietdocgiaUrl" id="chitietdocgiaUrl"/>
    <input type="hidden" value="<?php echo $urlTrasach ?>" name="urlTrasach" id="urlTrasach"/>
    </form>
</div>