<?php
$listGoodBooks = $this->getListGoodBooks();

if ($listGoodBooks->getSize()) :
?>
<div class="title">
    <a class="a-left" href="">Tuyển tập sách nổi bật</a>
</div>
<div class="home-books-content">
    <div class="goodbooks">
        <ul>
            <?php foreach($listGoodBooks as $book): ?>
            <li>
                <div class="">
                    <a href="<?php echo Mage::getUrl('thuvien/catalog_product/view',array('id'=>$book->getData('MaTpCom'))) ?>"><img src="<?php echo $this->getImages($book->getData('Hinh')) ?>" title="<?php echo $book->getData('TenTacPham')?>">
                    </a>
                </div>
                <div class="book-infor">
                    <div class="prodouct-name">
                        <a href="<?php echo Mage::getUrl('thuvien/catalog_product/view',array('id'=>$book->getData('MaTpCom'))) ?>" title="<?php echo $book->getData('TenTacPham')?>">
                            <?php echo $book->getData('TenTacPham') ?>
                        </a>
                    </div>

                    <?php if($book->getData('TapSo')): ?>
                        <div>Tập số: <?php echo $book->getData('TapSo')?></div>
                    <?php endif; ?>
                    <div> Tác giả: <a href="<?php echo Mage::getUrl('thuvien/tacgia/listp',array('id'=>$book->getData('MaKyHieuTg'))) ?>"><span class="tacgia">  <?php echo $book->getTacGia(); ?> </span></a></div>
                </div>
            </li>


            <?php endforeach ?>

        </ul>
    </div>
</div>
<?php endif; ?>