
<div class="title">
    <a class="a-left" href="">sách mới nhất</a>
    <a class="a-right" href="all"> &raquo; Tất cả</a>
</div>
<div class="home-books-content">
    <button class="prev-newbook">&nbsp;</button>
    <div class="newbook">
        <ul>

            <li>
                <div class=""> <img src="<?php echo $this->getSkinUrl('images/demobooks/10022.jpg') ?>">
                </div>
                <div class="book-infor">
                    <div class="prodouct-name"> Nhà Chỉ Kim </div>
                    <div> Tác giả: <span class="tacgia"> Huy Cận </span></div>
                </div>
            </li>
            <li>
                <div class=""> <img src="<?php echo $this->getSkinUrl('images/demobooks/10022.jpg') ?>" >
                </div>
                <div class="book-infor">
                    <div class="prodouct-name"> Nhà Chỉ Kim </div>
                    <div> Tác giả: <span class="tacgia"> Huy Cận </span></div>
                </div>
            </li>
            <li>
                <div class=""> <img src="<?php echo $this->getSkinUrl('images/demobooks/10022.jpg') ?>" >
                </div>
                <div class="book-infor">
                    <div class="prodouct-name"> Nhà Chỉ Kim </div>
                    <div> Tác giả: <span class="tacgia"> Huy Cận </span></div>
                </div>
            </li>
            <li>
                <div class=""> <img src="<?php echo $this->getSkinUrl('images/demobooks/10022.jpg') ?>" >
                </div>
                <div class="book-infor">
                    <div class="prodouct-name"> Nhà Chỉ Kim </div>
                    <div> Tác giả: <span class="tacgia"> Huy Cận </span></div>
                </div>
            </li>
            <li>
                <div class=""> <img src="<?php echo $this->getSkinUrl('images/demobooks/10022.jpg') ?>">
                </div>
                <div class="book-infor">
                    <div class="prodouct-name"> Nhà Chỉ Kim </div>
                    <div> Tác giả: <span class="tacgia"> Huy Cận </span></div>
                </div>
            </li>
            <li>
                <div class=""> <img src="<?php echo $this->getSkinUrl('images/demobooks/10022.jpg') ?>" >
                </div>
                <div class="book-infor">
                    <div class="prodouct-name"> Nhà Chỉ Kim </div>
                    <div> Tác giả: <span class="tacgia"> Huy Cận </span></div>
                </div>
            </li>
            <li>
                <div class=""> <img src="<?php echo $this->getSkinUrl('images/demobooks/10022.jpg') ?>" >
                </div>
                <div class="book-infor">
                    <div class="prodouct-name"> Nhà Chỉ Kim </div>
                    <div> Tác giả: <span class="tacgia"> Huy Cận </span></div>
                </div>
            </li>
            <li>
                <div class=""> <img src="<?php echo $this->getSkinUrl('images/demobooks/10022.jpg') ?>" >
                </div>
                <div class="book-infor">
                    <div class="prodouct-name"> Nhà Chỉ Kim </div>
                    <div> Tác giả: <span class="tacgia"> Huy Cận </span></div>
                </div>
            </li>
            <li>
                <div class=""> <img src="<?php echo $this->getSkinUrl('images/demobooks/10022.jpg') ?>">
                </div>
                <div class="book-infor">
                    <div class="prodouct-name"> Nhà Chỉ Kim </div>
                    <div> Tác giả: <span class="tacgia"> Huy Cận </span></div>
                </div>
            </li>
            <li>
                <div class=""> <img src="<?php echo $this->getSkinUrl('images/demobooks/10022.jpg') ?>">
                </div>
                <div class="book-infor">
                    <div class="prodouct-name"> Nhà Chỉ Kim </div>
                    <div> Tác giả: <span class="tacgia"> Huy Cận </span></div>
                </div>
            </li>
        </ul>
    </div>
    <button class="next-newbook">&nbsp;</button>
    <script type="text/javascript">
        jQuery(function() {
            jQuery(".newbook").jCarouselLite({
                 btnNext: ".next-newbook",
                 btnPrev: ".prev-newbook",
                 scroll: 6,
                 visible: 6
            });
        });
    </script>
</div>