<form name="danhsach" method="post" action="thuvien/adminhtml_danhsach/genarate" id="danhsach" >
   <h2> Danh sách tác phẩm</h2>
    <div>
        <select name="typelist">
            <option value="listtongquat">
                Danh sách tổng quát tác phẩm
            </option>
            <option value="listchitiet">
                Danh sách tác phẩm với những chi tiết
            </option>
            <option value="listmuclucnoidung">
                Danh sách tác phẩm theo Mục Lục - Nội Dung
            </option>
            <option value="listmlhb">
                Danh sách tác phẩm theo Mục Lục - Hình Bìa
            </option>
            <option value="listlinhvuc">
                Danh sách tác phẩm theo lĩnh vực
            </option>
            <option value="listtgdg">
                Danh sách tác phẩm theo tác giả, dịch giả, nhà xuất bản
            </option>
            <option value="listtheloai">
                Danh sách tác phẩm theo thể loại - sách bộ
            </option>
            <option value="listngaynhap">
                Danh sách tác phẩm theo ngày nhập
            </option>
            <option value="listngaymuon">
                Danh sách tác phẩm theo ngày mượn
            </option>
            <option value="listdangmuon">
                Danh sách tác phẩm đang mượn
            </option>
            <option value="listgiutruoc">
                Danh sách tác phẩm giữ trước
            </option>
        </select>
        <button type="submit" value="danhsach">Hiển thị danh sách</button>
    </div>

</form>