<script type="text/javascript">
var store_id;
var parent_id;
var data;
data = JSON.parse($('parent_id').value);
parent_id = data.parent_id;
if (parent_id != '1'){
	$('store_id').disable();
	$('store_id').setOpacity(0.5);
	window.setStore();
}
if (parent_id == '1'){
	$('store_id').enable();
	$('store_id').setOpacity(1);
}

Event.observe($('parent_id'),'change',function(event){
	data = JSON.parse($('parent_id').value);
	parent_id = data.parent_id;
	if (parent_id != '1'){
		$('store_id').disable();
		$('store_id').setOpacity(0.5);
		window.setStore();
	}
	if (parent_id == '1'){
		$('store_id').enable();
		$('store_id').setOpacity(1);
	}
});

function setStore(){
	store_id = data.store_id + "";
	store_id = store_id.split(',');
	$('store_id').descendants()[0].selected=true ;
	store = $('store_id').descendants();
	store.each(function (store){
		 store_id.each(function(store_id){
			if(store.value == store_id){
				store.selected = true;
				throw $break;
			}else store.selected = false;
		});
	});
}

function findStore(store_id){
	store_id.each() 
}
</script>

