<script type="text/javascript">
<!--
	function save_order(){

		var arrInput = document.getElementsByClassName('order_cat');

		var params = "";
		for(var i=0;i<arrInput.length;i++){
			params += arrInput[i].title + "-" + arrInput[i].value + "|";
		}
		//window.location = "<?php //echo $this->getUrl('*/*/setOrder') ?>items/"+params; 
		new Ajax.Request('<?php echo Mage::helper('adminhtml')->getUrl('*/*/setOrder') ?>', {
	        method: 'post',
	        parameters: { items: params}
	    });
	}
//-->
</script>
<?php
/**
 * Template for Mage_Adminhtml_Block_Widget_Grid
 *
 *  getId()
 *  getCollection()
 *  getColumns()
 *  getPagerVisibility()
 *  getVarNamePage()
 */
$numColumns = sizeof($this->getColumns());
?>
<?php if($this->getCollection()): ?>
    <?php if($this->canDisplayContainer()): ?>
        <?php if($this->getGridHeader()): ?>
        <div class="content-header">
            <table cellspacing="0">
                <tr>
                    <td style="width:50%;"><h2><?php echo $this->getGridHeader(); ?></h2></td>
                </tr>
            </table>
        </div>
        <?php endif ?>

        <div id="<?php echo $this->getId() ?>">
    <?php else: ?>
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php endif; ?>
<?php if($this->getPagerVisibility() || $this->getExportTypes() || $this->getFilterVisibility()): ?>
    <table cellspacing="0" class="actions">
        <tr>
        <td>&nbsp;</td>
    <?php if($this->getExportTypes()): ?>
        <td class="export a-right">
            <img src="<?php echo $this->getSkinUrl('images/icon_export.gif') ?>" alt="" class="v-middle"/>&nbsp; <?php echo $this->__('Export to:') ?>
            <select name="<?php echo $this->getId() ?>_export" id="<?php echo $this->getId() ?>_export" style="width:8em;">
            <?php foreach ($this->getExportTypes() as $_type): ?>
                <option value="<?php echo $_type->getUrl() ?>"><?php echo $_type->getLabel() ?></option>
            <?php endforeach; ?>
            </select>
            <?php echo $this->getExportButtonHtml() ?>
        </td>
    <?php endif; ?>
        <td class="filter-actions a-right">
            <?php echo $this->getMainButtonsHtml() ?>
        </td>
        </tr>
    </table>
<?php endif; ?>
<?php if($this->getMassactionBlock()->isAvailable()): ?>
<?php echo $this->getMassactionBlockHtml() ?>
<?php endif ?>
<div class="grid">
    <div class="hor-scroll">
    <table cellspacing="0" class="data" id="<?php echo $this->getId() ?>_table">
        <?php foreach ($this->getColumns() as $_column): ?>
        <col <?php echo $_column->getHtmlProperty() ?> />
        <?php if ($_column->getEditable() && !$_column->getEditOnly()) : ?>
        <col <?php echo $_column->getHtmlProperty() ?> />
        <?php endif ?>
        <?php endforeach; ?>
        <?php if ($this->getHeadersVisibility() || $this->getFilterVisibility()): ?>
            <thead>
                <?php if ($this->getHeadersVisibility()): ?>
                    <tr class="headings">
                    <?php foreach ($this->getColumns() as $_column): ?>
                        <th<?php echo $_column->getHeaderHtmlProperty() ?>><span class="nobr"><?php echo $_column->getHeaderHtml() ?></span></th>
                    <?php endforeach; ?>
                    </tr>
                <?php endif; ?>
                <?php if ($this->getFilterVisibility()): ?>
                    <tr class="filter">
                    <?php $i=0;foreach ($this->getColumns() as $_column): ?>
                        <th<?php echo $_column->getHeaderHtmlProperty() ?>><?php echo $_column->getFilterHtml() ?></th>
                    <?php endforeach; ?>
                    </tr>
                <?php endif ?>
            </thead>
        <?php endif; ?>
        <?php if ($this->getCountTotals()): ?>
            <tfoot>
                <tr class="totals">
                <?php foreach ($this->getColumns() as $_column): ?>
                    <th class="<?php echo $_column->getCssProperty() ?>"><?php echo ($_column->hasTotalsLabel()) ? $_column->getTotalsLabel() : $_column->getRowField($_column->getGrid()->getTotals()) ?>&nbsp;</th>
                <?php endforeach; ?>
                </tr>
            </tfoot>
        <?php endif; ?>

        <tbody>
        <?php if (($this->getCollection()->getSize()>0) && (!$this->getIsCollapsed())): ?>
        <?php
        			$i=0;
        			$GridIds = "";
        			$catModel = Mage::getModel('cmspro/category');
        			$cats = $catModel->getTreeCategoryAdmin(false,false);

        			foreach($cats as $cat){
        				$catObj = $catModel->load($cat['value']);
        				$GridIds .=$cat['value']."," ;
        				
        			?>
					<tr title="<?php echo $this->getUrl('cmspro_admin/adminhtml_category/edit',array('id'=>$cat['value'])); ?>" class="<?php echo ($i==0) ? "even":""?> pointer" id="">
						<td class="a-center "><input type="checkbox" class="massaction-checkbox" value="<?php echo $cat['value'] ?>" name="category"></td>
						<td class="a-right "><?php echo $cat['value']; ?></td>
						<td class="a-left "><?php echo $cat['label']; ?></td>
						<td class="a-left "><?php echo $catObj->getCreatedTime(); ?></td>
						<td class="a-left "><input type="text" class="order_cat" title="<?php echo $catObj->getCategoryId(); ?>" style="width:60px;" id="order_cat<?php echo $cat['value'] ?>" value="<?php echo $catObj->getOrderCat();?>"></td>
						<td class="a-left "><?php if($catObj->getStatus()==1){ echo Mage::helper('cmspro')->__('Enabled'); }else{ echo Mage::helper('cmspro')->__('Disabled'); } ?></td>
						<td class=" last"><a href="<?php echo $this->getUrl('cmspro_admin/adminhtml_category/edit',array('id'=>$cat['value'])); ?>"><?php echo Mage::helper('cmspro')->__('Edit'); ?></a></td>
					</tr>
					<?php if($i==0) {$i=1;}else{$i=0;} ?>
				<?php } ?>
        
        <?php elseif ($this->getEmptyText()): ?>
            <tr>
                <td class="empty-text <?php echo $this->getEmptyTextClass() ?>" colspan="100"><?php echo $this->getEmptyText() ?></td>
            </tr>
        <?php endif; ?>
        </tbody>

    </table>
    </div>
</div>
<?php if($this->canDisplayContainer()): ?>
</div>
<script type="text/javascript">
//<![CDATA[
    <?php echo $this->getJsObjectName() ?> = new varienGrid('<?php echo $this->getId() ?>', '<?php echo $this->getGridUrl() ?>', '<?php echo $this->getVarNamePage() ?>', '<?php echo $this->getVarNameSort() ?>', '<?php echo $this->getVarNameDir() ?>', '<?php echo $this->getVarNameFilter() ?>');
    <?php echo $this->getJsObjectName() ?>.useAjax = '<?php echo $this->getUseAjax() ?>';
    <?php if($this->getRowClickCallback()): ?>
        <?php echo $this->getJsObjectName() ?>.rowClickCallback = <?php echo $this->getRowClickCallback() ?>;
    <?php endif; ?>
    <?php if($this->getCheckboxCheckCallback()): ?>
        <?php echo $this->getJsObjectName() ?>.checkboxCheckCallback = <?php echo $this->getCheckboxCheckCallback() ?>;
    <?php endif; ?>
    <?php if($this->getRowInitCallback()): ?>
        <?php echo $this->getJsObjectName() ?>.initRowCallback = <?php echo $this->getRowInitCallback() ?>;
        <?php echo $this->getJsObjectName() ?>.initGridRows();
    <?php endif; ?>
    <?php if($this->getMassactionBlock()->isAvailable()): ?>
    <?php echo $this->getMassactionBlock()->getJavaScript() ?>
    <?php endif ?>
//]]>
</script>
<?php endif; ?>
<?php endif ?>